### ISSUE TITLE
在android5.0上第二行歌词没有颜色变化

### ISSUE THREAD

**Issue by MrR0990** [zhangliangming/HappyMusicPlayer#1]
在android5.0上第二行歌词没有颜色变化

**Comment by zhangliangming** [comment]
不好意思哦，我不知已经有人看到我的播放器了。你好？歌词一定要是ksc格式的哦。还有，现在在歌词方面修复了。我手机也是android5.0的。最新的是可以看到了。最新版本 添加的功能还是 比较多，具体 你自己看 readme.txt文件

**Comment by zhangliangming** [comment]
关于代码方面 还请大神 先不要到其它 地方发布哦

**Comment by cwhCp** [comment]
你好 你这个可以放在android studio里吗？如果可以有没有步骤或者给个链接

**Comment by zhangliangming** [comment]
你好，因为当时是在eclipse里面开发的，目前我还没有弄studio版本的，所以没有步骤。或者你从网上看一下，怎样把eclipse的项目移植到studio里面。
不好意思。。。。。

**Comment by zhangliangming** [comment]
https://github.com/zhangliangming/HappyPlayer-AS.git    这个as版本的，你们可以看看
