### ISSUE TITLE
搜索完歌曲以后，点击某个歌曲会崩溃

### ISSUE THREAD

**Issue by guoxj** [zhangliangming/HappyMusicPlayer#2]
好像是排序列表的问题呢

**Comment by guoxj** [comment]
只是第一次会出问题。

**Comment by zhangliangming** [comment]
bug还是有的，哈哈。你可以用一下 最新版本的，到我的GitHub上面看HappyPlayer2016-06-09-new

**Comment by guoxj** [comment]
好的。谢谢你这么无私的奉献啦

**Comment by zhangliangming** [comment]
歌词方面，还是沿用了旧版本的，所以看起来不流畅。最近，在弄其它的事情，等弄完了，再优化一下，歌词方面的问题和更换成as开发。
